// <auto-generated>
// This code was generated by TagConstantsGenerator.
// </auto-generated>

using UnityEngine;

namespace Constants
{
	public sealed class Tag
	{
		public static readonly string Untagged = "Untagged";
		public static readonly string Respawn = "Respawn";
		public static readonly string Finish = "Finish";
		public static readonly string EditorOnly = "EditorOnly";
		public static readonly string MainCamera = "MainCamera";
		public static readonly string Player = "Player";
		public static readonly string GameController = "GameController";
		
		public sealed class Handle
		{
			public static readonly TagHandle Untagged = TagHandle.GetExistingTag("Untagged");
			public static readonly TagHandle Respawn = TagHandle.GetExistingTag("Respawn");
			public static readonly TagHandle Finish = TagHandle.GetExistingTag("Finish");
			public static readonly TagHandle EditorOnly = TagHandle.GetExistingTag("EditorOnly");
			public static readonly TagHandle MainCamera = TagHandle.GetExistingTag("MainCamera");
			public static readonly TagHandle Player = TagHandle.GetExistingTag("Player");
			public static readonly TagHandle GameController = TagHandle.GetExistingTag("GameController");
		}
	}
}