name: WebGPU Build and Deploy to Github Pages

on:
  push:
    branches: ["release"]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  Unity-Build:
    name: Build for WebGL
    runs-on: ubuntu-latest
    
    steps:
      # 不要なツールを削除して容量確保
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: false

      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: MicroMacro/Library
          key: Library-${{ runner.os }}-6000.1.2f1-${{ hashFiles('MicroMacro/Assets/**', 'MicroMacro/Packages/**', 'MicroMacro/ProjectSettings/**') }}
          restore-keys: |
            Library-${{ runner.os }}-6000.1.2f1-
            Library-${{ runner.os }}-

      # Unity Build
      - name: Run the WebGL Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          projectPath: MicroMacro
          unityVersion: 6000.1.2f1
          allowDirtyBuild: true
          buildsPath: build

      - name: Debug - List files
        run: ls -R

      #  所有権を修正してから.nojekyllを作成（これが無いとUnityのファイルが無視されて404になる）
      - name: Fix Permissions & Create .nojekyll
        run: |
          sudo chown -R $USER:$USER build
          touch build/WebGL/WebGL/.nojekyll

      # Upload 
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/WebGL/WebGL

      - name: Discord Notification
        if: always()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "WebGPU Build Status"
          description: |
            Build: ${{ env.BUILD_NAME }}
            Commit: ${{ env.COMMIT_HASH }}
          color: 0x00ff00 
          url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  deploy:
    name: Deploy to GitHub Pages
    needs: Unity-Build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
